plugins {
    id "fabric-loom" version "1.17.20"
}

version = "1.13.1-yarn"
group = "baritone"

repositories {
    maven {
        name = "babbaj-repo"
        url = "https://babbaj.github.io/maven/"
    }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.4"
    mappings "net.fabricmc:yarn:1.21.4+build.8:v2"
    modImplementation "net.fabricmc:fabric-loader:0.16.9"

    compileOnly "net.fabricmc:sponge-mixin:0.15.4+mixin.0.8.7"
    annotationProcessor "net.fabricmc:sponge-mixin:0.15.4+mixin.0.8.7"
    compileOnly files("META-INF/jars/nether-pathfinder-1.4.1.jar")
    implementation "com.google.code.findbugs:jsr305:3.0.2"
}


loom {
    mixin {
        defaultRefmapName = "mixins.baritone-meteor-refmap.json"
    }
}

tasks.named("processResources") {
    from("fabric.mod.json")
    from("mixins.baritone-meteor.json")
    from("META-INF/jars") {
        into("META-INF/jars")
    }
    filesMatching("fabric.mod.json") {
        expand(version: project.version)
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 21
}
